

%%   Author: Jens M. Hovem
%%   Copyright 2011 Acoustic Research Center, NTNU
%%   Revised: 2011/01/11


%% Plots the beampatteren for a single frequency generated by
%% getbeamspec(para, initial_angle,1);
%% Only for visualisering and not used in any other calculations
clear BB; clear theta;
N=para.nfft;n=1:N;
fs=para.fs;Ne=para.Ne;
delta_x=para.delta_x;c=1500;
f=(0:N-1)*fs/N;
M=90;
freq=para.frequency;
Nf=length(freq);
for n=1:1:Nf
    
    for m=1:M
        initial_angle=pi*m/M;
        theta(m)=initial_angle;
        beamspectrum  = getbeamspec(para, initial_angle,1);
        BB(m,:)=abs(beamspectrum);
    end
    BB_dB=20*log10(BB)+40;
    BB_dB(BB_dB<0)=0;
    figure(50+n) ; clf
    fonts=12; set(gcf,'DefaultTextFontSize', fonts,'DefaultAxesFontSize', fonts);
    
    frequency =freq(n);
    k=find(f==frequency);
    polar([theta -theta],[BB_dB(:, k)' BB_dB(:, k)'],'b' )
        title(['Array beam pattern for '  num2str(frequency ) ' Hz'])
end
